#!/usr/bin/env python3
"""
Data to Word Analysis Report — Generation Script
Usage: python3 gen_report.py <output_path> '<report_json>'
"""
import sys, json

try:
    from docx import Document
    from docx.shared import Pt, Inches, Cm, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.table import WD_TABLE_ALIGNMENT
    from docx.oxml.ns import qn
except ImportError:
    print("Missing python-docx, please run: pip install python-docx")
    sys.exit(1)


def set_cell_shading(cell, color_hex: str):
    """Set cell background color"""
    shading = cell._element.get_or_add_tcPr()
    shading_elm = shading.makeelement(qn("w:shd"), {
        qn("w:fill"): color_hex,
        qn("w:val"): "clear",
    })
    shading.append(shading_elm)


def add_styled_table(doc, headers: list, rows: list):
    """Add styled table"""
    table = doc.add_table(rows=1 + len(rows), cols=len(headers))
    table.alignment = WD_TABLE_ALIGNMENT.CENTER

    # Header row
    for i, h in enumerate(headers):
        cell = table.rows[0].cells[i]
        cell.text = h
        for p in cell.paragraphs:
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            for run in p.runs:
                run.font.size = Pt(10)
                run.font.bold = True
                run.font.color.rgb = RGBColor(255, 255, 255)
                run.font.name = "Microsoft YaHei"
                run._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
        set_cell_shading(cell, "4472C4")

    # Data rows
    for r_idx, row in enumerate(rows):
        for c_idx, val in enumerate(row):
            cell = table.rows[r_idx + 1].cells[c_idx]
            cell.text = str(val) if val is not None else ""
            for p in cell.paragraphs:
                for run in p.runs:
                    run.font.size = Pt(10)
                    run.font.name = "Microsoft YaHei"
                    run._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
            if r_idx % 2 == 1:
                set_cell_shading(cell, "F2F2F2")

    doc.add_paragraph("")  # Spacing after table
    return table


def generate_report(output_path: str, report: dict):
    doc = Document()

    # ── Page Setup ──
    section = doc.sections[0]
    section.top_margin = Cm(2.5)
    section.bottom_margin = Cm(2.5)
    section.left_margin = Cm(2.8)
    section.right_margin = Cm(2.8)

    # ── Title ──
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run(report.get("title", "Data Analysis Report"))
    run.font.size = Pt(22)
    run.font.bold = True
    run.font.color.rgb = RGBColor(0x1A, 0x3C, 0x6E)
    run.font.name = "Microsoft YaHei"
    run._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")

    # Subtitle separator line
    sep = doc.add_paragraph()
    sep.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = sep.add_run("━" * 40)
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(0x44, 0x72, 0xC4)

    doc.add_paragraph("")

    # ── Content ──
    for section_data in report.get("sections", []):
        # Heading
        heading = doc.add_heading(level=1)
        run = heading.add_run(section_data["heading"])
        run.font.size = Pt(16)
        run.font.color.rgb = RGBColor(0x1A, 0x3C, 0x6E)
        run.font.name = "Microsoft YaHei"
        run._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")

        # Paragraphs
        for text in section_data.get("paragraphs", []):
            p = doc.add_paragraph()
            p.paragraph_format.space_after = Pt(6)
            p.paragraph_format.line_spacing = 1.5
            run = p.add_run(text)
            run.font.size = Pt(11)
            run.font.name = "Microsoft YaHei"
            run._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")

        # Table
        tbl = section_data.get("table")
        if tbl and tbl.get("headers") and tbl.get("rows"):
            add_styled_table(doc, tbl["headers"], tbl["rows"])

        if section_data != report["sections"][-1]:
            doc.add_paragraph("")

    # ── Footer ──
    footer_p = doc.add_paragraph()
    footer_p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    run = footer_p.add_run("— Report automatically generated by AI —")
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)
    run.font.italic = True

    doc.save(output_path)
    print(f"✅ Report saved: {output_path}")


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python3 gen_report.py <output_path> '<report_json>'")
        sys.exit(1)

    try:
        report = json.loads(sys.argv[2])
    except json.JSONDecodeError as e:
        print(f"❌ JSON parsing failed: {e}")
        sys.exit(1)

    generate_report(sys.argv[1], report)